export const CUSTOM_COLORS: Record<string, { name: string; hex: string }> = {
  "amarelo": { name: "Amarelo", hex: "#FFC600" },
  "azul claro": { name: "Azul claro", hex: "#B2D7E7" },
  "azul escuro": { name: "Azul Escuro", hex: "#00205B" },
  "azul turquesa": { name: "Azul Turquesa", hex: "#4CC5CD" },
  "bege": { name: "Bege", hex: "#D6C4A8" },
  "branco": { name: "Branco", hex: "#FFFFFF" },
  "cereja": { name: "Cereja", hex: "#C71149" },
  "colorido": { name: "Colorido", hex: "#CCCCCC" },
  "coral": { name: "Coral", hex: "#FF6B6B" },
  "lilás": { name: "Lilás", hex: "#D7C6E6" },
  "marrom": { name: "Marrom", hex: "#4A2C2A" },
  "marsala": { name: "Marsala", hex: "#582534" },
  "off white": { name: "Off White", hex: "#F4F1EC" },
  "pêssego": { name: "Pêssego", hex: "#FFA07A" },
  "preto": { name: "Preto", hex: "#2D2926" },
  "rosa claro": { name: "Rosa claro", hex: "#FADADD" },
  "rosa pink": { name: "Rosa pink", hex: "#DA1884" },
  "roxo": { name: "Roxo", hex: "#7F3F98" },
  "transparente": { name: "Transparente", hex: "#F8F8F8" },
  "verde água": { name: "Verde água", hex: "#78D5D7" },
  "verde claro": { name: "Verde claro", hex: "#A8D18D" },
  "verde escuro": { name: "Verde escuro", hex: "#00573F" },
  "vermelho": { name: "Vermelho", hex: "#C8102E" },
  "vinho": { name: "Vinho", hex: "#651E38" },
};
